
incidents = (
	("", "------------"),
	("robbery", "Robbery"),
	("accident", "Accident"),
	("murder", "Murder"),
	("burglary", "Burglary"),)

incident_time = (
	("", "------------"),
	("0:00 - 08:00", )
)

countries = (
	("", "------------"),
	("cw", "CW"),
	("bon", "BON"),
	("aua", "AUA"),)

locations = (
	("", "------------"),
	("abrahamsz", "Abrahamsz"),
	("Amerikanenkamp", "Amerikanenkamp"),
	("Arrarat", "Arrarat"),
	("Barbouquet", "Barbouquet"),
	("Batavierwijk", "Batavierwijk"),
	("Bellevue", "Bellevue"),
	("Biesheuvel", "Biesheuvel"),
	("Bivak", "Bivak"),
	("Blauw", "Blauw"),
	("Bloemfontein", "Bloemfontein"),
	("Bonam", "Bonam"),
	("Bottelier", "Bottelier"),
	("Brakkeput", "Brakkeput"),
	("Brakkeput Abou", "Brakkeput Abou"),
	("Brakkeput Ariba", "Brakkeput Ariba"),
	("Brievengat", "Brievengat"),
	("Buena Vista", "Buena Vista"),
	("Cabo Verde", "Cabo Verde"),
	("Cas Cora", "Cas Cora"),
	("Cas Grandi", "Cas Grandi"),
)

# 	(, "Charo"),
# 	(, "Cher Asile"),
# 	(, "Christoffel"),
# 	(, "Cocorie"),
# 	(, "Cocowijk"),
# 	(, "Colon"),
# 	(, "Coronet"),
# 	(, "Damacor"),
# 	(, "De Savaan"),
# 	(, "Dein"),
# 	(, "Dok"),
# 	(, "Domi"),
# 	(, "Dominguito"),
# 	(, "Emmastad"),
# 	(, "Esperansa"),
# 	(, "Fleur de Marie"),
# 	(, "Flip"),
# 	(, "Fortuna"),
# 	(, "Fortuna Abou"),
# 	(, "Fortuna Ariba"),
# 	(, "Francia"),
# 	(, "Gaitu"),
# 	(, "Gasparitu"),
# 	(, "Gato"),
# 	(, "Gibraltar")),
# 	(, "Girouette")),
# 	(, "Goede Hoop")),
# 	(, "Groot Davelaar")),
# 	(, "Groot Kwartier")),
# 	(, "Groot Piscadera")),
# 	(, "Habaai")),
# 	(, "Hanenberg")),
# 	(, "Harmonie")),
# 	(, "Hato")),
# 	(, "Hoenderberg")),
# 	(, "Jan Boos")),
# 	(, "Jan Luis")),
# 	(, "Jan Sofat")),
# 	(, "Jan Thiel")),
# 	(, "Jandoret")),
# 	(, "Janwe")),
# 	(, "Jonchi")),
# 	(, "Jongbloed")),
# 	(, "Jonisberg")),
# 	(, "Juan Domingo")),
# 	(, "Juan Hato")),
# 	(, "Juanota")),
# 	(, "Julianadorp")),
# 	(, "Kanga")),
# 	(, "Katoentuin")),
# 	(, "Kent U Zelf")),
# 	(, "Kintjan")),
# 	(, "Kirindongo Abou")),
# 	(, "Klein Davelaar")),
# 	(, "Klein Sint Michiel")),
# 	(, "Kolonchi")),
# 	(, "Koraal Partier")),
# 	(, "Koraal Specht")),
# 	(, "Koraal Tabak")),
# 	(, "Kortijn")),
# 	(, "Kustbatterij")),
# 	(, "Labadera")),
# 	(, "Lagun")),
# 	(, "Leliënberg",))
# 	(, "Libie"),
# 	(, "Kwarchi"),
# 	(, "Ma Louia"),
# 	(, "Mahaai"),
# 	(, "Mahuma"),
# 	(, "Marchena"),
# 	(, "Maria Maai"),
# 	(, "Marie Pampoen"),
# 	(, "Nieuwe Haven"),
# 	(, "Matancia"),
# 	(, "Mon Repos"),
# 	(, "Montaña Abou"),
# 	(, "Montaña Rey"),
# 	(, "Monte Carmelo"),
# 	(, "Monte Verde"),
# 	(, "Muizenberg"),
# 	(, "Mundo Nobo"),
# 	(, "Nabij Vetter"),
# 	(, "Nieuw Nederland"),
# 	(, "Noord Zapateer"),
# 	(, "Normandie"),
# 	(, "Otrabanda"),
# 	(, "Oudewater"),
# 	(, "Pannekoek"),
# 	(, "Papaya Abou"),
# 	(, "Paradijs"),
# 	(, "Parera"),
# 	(, "Pietermaai"),
# 	(, "Piscadera"),
# 	(, "Popo"),
# 	(, "Pos Cabai"),
# 	(, "Punda"),
# 	(, "Rancho"),
# 	(, "Rooi Catochi"),
# 	(, "Rooi Santu"),
# 	(, "Ronde Klip"),
# 	(, "Romar"),
# 	(, "Rosendaal"),
# 	(, "Rozenburg"),
# 	(, "Rust En Vrede"),
# 	(, "Sabana Cras"),
# 	(, "Sabana Hundu"),
# 	(, "Saliña"),
# 	(, "Salsbach"),
# 	(, "San Fuego"),
# 	(, "San Mateo"),
# 	(, "Sans Souci"),
# 	(, "Santa Barbara"),
# 	(, "Santa Helena"),
# 	(, "Santa Maria"),
# 	(, "Santa Catharina"),
# 	(, "Santa Rosa"),
# 	(, "Scharloo"),
# 	(, "Schelpwijk"),
# 	(, "Scherpenheuvel"),
# 	(, "Semikok"),
# 	(, "Seru Grandi"),
# 	(, "Seru Mahuma"),
# 	(, "Seru Fortuna"),
# 	(, "Seru Kandela"),
# 	(, "Seru Lora"),
# 	(, "Seru Mahuma"),
# 	(, "Seru Papaya"),
# 	(, "Seru Pretu"),
# 	(, "Sint Jacob"),
# 	(, "Sint Joris"),
# 	(, "Sint Michiel"),
# 	(, "Sint Willibrordus"),
# 	(, "Souax"),
# 	(, "Soto"),
# 	(, "Spaanse Water"),
# 	(, "Steenrijk"),
# 	(, "Stenen Koraal"),
# 	(, "Suffisant"),
# 	(, "Toni Kunchi"),
# 	(, "Trai Seru"),
# 	(, "Van Engelen"),
# 	(, "Veeris"),
# 	(, "Vetter"),
# 	(, "Vredenberg"),
# 	(, "Wacao"),
# 	(, "Wanapa"),
# 	(, "Weis"),
# 	(, "Welgelegen"),
# 	(, "Westpunt"),
# 	(, "Weto"),
# 	(, "Wishi"),
# 	(, "Zeelandia"),
# 	(, "Zeewijk"),
# 	(, "Zegu"),
# 	(, "Zuurzak"),
# ]